version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: estagioSQL
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: serproestagio
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
